### ISSUE TITLE
Unexpected Image Rotation

### ISSUE THREAD

**Issue by c9mbundy** [JimBobSquarePants/ImageProcessor#838] opened 2021-06-29 08:04 UTC
Hi,

ImageProcessor:  v2.9.1
ImageProcessor.Web: v4.12.1
ImageProcessor.Web.Plugins.AzureBlobCache: v1.7.1

I have an Umbraco-Cloud V7 site (v7.15.7) with some large vertical-aspect images stored on AzureBlobStorage, and using ImageProcessor to manipulate them and store the results in a cache container.

The native image stored in my /media container seems fine, and the cached version in my /cache container also seems ok.

However, when I add anything to trigger an ImageProcessor action, it flips the image on its side for some reason (please excuse the appearance of toilet humor below - it just happens to be the example my client gave)

e.g. [https://www.cloud9online.com.au/media/1262/ic17167-1-1-01.jpg](https://www.cloud9online.com.au/media/1262/ic17167-1-1-01.jpg)

e.g. [https://www.cloud9online.com.au/media/1262/ic17167-1-1-01.jpg?width=768](https://www.cloud9online.com.au/media/1262/ic17167-1-1-01.jpg?width=768)

Of course, both of these results are coming out of the /cache container on the Azure Storage, as they've been processed by ImageProcessor.

I also notice the same thing is happening in the Umbraco V7 media-picker, with it flipping the large image on its side for cropped thumbnails, but showing correctly for the full-size image of the Media-Library - so it's not just my rubbish code that's doing it.

However, I have other (albeit smaller) vertical-aspect images where this doesn't happen, and everything behaves as expected.

e.g. [https://www.cloud9online.com.au/media/1261/acrylic-block-production.jpg](https://www.cloud9online.com.au/media/1261/acrylic-block-production.jpg)

e.g. [https://www.cloud9online.com.au/media/1261/acrylic-block-production.jpg?width=768](https://www.cloud9online.com.au/media/1261/acrylic-block-production.jpg?width=768)

Not sure what I'm doing wrong, but it must be something pretty basic, as this is just requesting a very simple crop via ImageProcessor as far as I can see?

**Comment by JimBobSquarePants** [comment] 2021-06-29 09:17
This screams Exif handling to me. @ronaldbarendse what’s Umbraco’s default metadata preservation mode?

**Comment by c9mbundy** [comment] 2021-06-29 10:07
I'm afraid that images are way outside my comfort zone, but I did a bit more testing, and found that I could get it to to behave as expected, by loading the troublesome image into photoshop, taking a rasterized copy of it, pasting that into a new item, and exporting it as a jpg. Of course, this is a real 'bash it until it works' approach, in lieu of actually understanding the problem - hah!

e.g. [https://www.cloud9online.com.au/media/1262/ic17167-1-1-01.jpg](https://www.cloud9online.com.au/media/1262/ic17167-1-1-01.jpg)

e.g. [https://www.cloud9online.com.au/media/1263/ic17167-1-1-01.jpg?width=768](https://www.cloud9online.com.au/media/1263/ic17167-1-1-01.jpg?width=768)

In windows explorer, the images report having the same dimensions, but the newer image is much larger. I can also see that the original version has come from an iPhone.
 
The other thing I now noticed (don't know why I didn't before) is that the first version reports it's width/height dimensions in reverse in the Umbraco Media-Library manager, whereas the 2nd (copied/exported) version gets them correct. i.e. for some reason the 1st version shows the width as height, and the height as width, even though they show correct in windows. 

I'm assuming this is the area where the issue lies, and obviously I now at least have a workaround, but someone will have a fair bit of work to do if the issue is in Umbraco-7 as I don't like my chances of getting a fix to that.

**Comment by JimBobSquarePants** [comment] 2021-06-29 10:26
Its EXIF handling. Here’s a workaround.

https://imageprocessor.org/imageprocessor-web/imageprocessingmodule/autorotate/

it’s also not a bug so I’m closing this.

**Closed by JimBobSquarePants** 2021-06-29 10:26 UTC

**Comment by ronaldbarendse** [comment] 2021-06-29 11:56
Umbraco does have `preserveExifMetaData="true"` as default, so the orientation EXIF metadata would be preserved after resizing. You can disable this setting to remove metadata from all processed requests or add the `?meta=false` query string to the URLs you want.

As James commented, you can also enable auto rotation to ensure ImageProcessor uses the EXIF orientation, but make sure to also remove the EXIF metadata (as the documentation also states).

**Comment by c9mbundy** [comment] 2021-06-29 22:18
@JimBobSquarePants  @ronaldbarendse Thanks for that assistance.

Please excuse the continued questions, as clearly this is an Umbraco focused issue, rather than an ImageProcessor issue, but I'm afraid is a bit outside my area of expertise. 

I can see the preserveExifMetaData="true" attribute in my Umbraco processing.config file.

When I upload the portrait image to the Media-Library, the display of the original image is portrait but width/height values report as landscape, so I presume the Exif orientation exists at that point and is being honored by the browser.

However, when I the download the processed images, the Exif value seems to be is missing, and they are displaying as landscape.

Not sure what is going on there, as I would have thought that if the preserveExifMetaData attribute is set to "true" then this behavior should not be happening?

I also note there is an attribute metaDataMode="None" which has come from the ImageProcessor.Web.Config transform file, and I don't actually know what that does, as I haven't uncovered the documentation for that - could that be the culprit?

**Comment by JimBobSquarePants** [comment] 2021-06-30 01:28
Ah right, they've turned off metadata preservation.

The enum looks like this. Choosing any option other than `None` will preserve critical EXIF metadata like rotation.

https://github.com/JimBobSquarePants/ImageProcessor/blob/a94fb903e49f6fa5f47c6ea58d27af55ce8ff89c/src/ImageProcessor/MetaDataMode.cs#L10-L39

**Comment by c9mbundy** [comment] 2021-06-30 02:26
@JimBobSquarePants - Cool and thanks again for your assistance.

**Comment by ronaldbarendse** [comment] 2021-06-30 08:50
Umbraco only sets `preserveExifMetaData="true"` (as [initial setting](https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Web.UI/config/imageprocessor/processing.config#L2) and [NuGet transform](https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/build/NuSpecs/tools/processing.config.install.xdt#L1)), but the `ImageProcessor.Web` transform turns both off:

https://github.com/JimBobSquarePants/ImageProcessor/blob/9bdb270ca285da2680c601d3800c28e059f4a979/src/ImageProcessor.Web/Configuration/Resources/processing.config.transform#L1

Looking at the config defaults, Umbraco does set the correct one to preserve EXIF metadata:
https://github.com/JimBobSquarePants/ImageProcessor/blob/4af8de4a6376d9426fadd5c4596bc1de187899c0/src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs#L26-L44

**Comment by JimBobSquarePants** [comment] 2021-06-30 09:30
They need to fix their config handling then
