### ISSUE TITLE
Animated GIF Quality Loss

### ISSUE THREAD

**Issue by jstrugnell** [JimBobSquarePants/ImageProcessor#245] opened 2015-10-23 12:44 UTC
Hi, we've recently upgraded to the latest ImageResizer Nuget package (Core V2.3, Web V4.4.0) and have noticed a problem with the quality of Animated GIFs when resized. For example, this image here loads just fine when left at default size - 

http://jamessouth.me/media/1009/mccoy-kirk.gif

However, if you apply a width or height etc. then the quality drops noticeably.

http://jamessouth.me/media/1009/mccoy-kirk.gif?width=300

This is even if the width and image are the same as the original. This didn't happen on the previous version that we were using. Is this a known issue?

Thanks,
James.

**Comment by christopherbauer** [comment] 2015-10-23 12:52
Hi James,

Can you include the code you're using so we can repro?

**Comment by jstrugnell** [comment] 2015-10-23 13:03
Hi Chris, 

What do you mean by code exactly? The above example URLs demonstrate the issue and this is on James South's own site? I can explain our scenario a bit further. We are running Umbraco 7.26 but as mentioned above we have upgraded the Image Processor packages. We are also using the ImageProcessor.Config package and James' Azure FileSystemProvider that enables Media content to be stored in the media directory...

I'm not sure if any of that is relevant or helpful but I've not written any custom code, other than HTML.

**Comment by JimBobSquarePants** [comment] 2015-10-23 13:32
I'm using gifsicle to crush gifs down as the standard .NET encoder doesn't use LZW encoding. I'll have a look at it to see if I can tweak the settinsg to improve the color output.

**Comment by JimBobSquarePants** [comment] 2015-10-26 04:38
Hey @jstrugnell Do you have another example of a gif with reduced quality? One processed using the base library, not the web extension.

That linked image is a special one that actually has more colours than gifs normally allow. (It's possible for gifs to have more than 256 colors though the .NET encoder cannot deal with that) so there will always be a reduction in quality when processing that one.

I'd like to confirm that the gifsicle post-processing is the cause of any reduction in quality.

**Comment by jstrugnell** [comment] 2015-10-30 12:48
Hi, sorry for the delay in coming back to you. I've been on annual leave.. anyway, the situation has got a bit stranger. We're using Azure slots and I had seen this issue on an upgraded UAT slot. When I switched with the production slot the problem didn't occur in the production site. So I put it down to a glitch. Only I then later looked at the UAT slot again (that which was previously PROD) and could still see the issue there. This baffles me as that was basically the old live site where it worked fine. 

Anyway I attach an example GIF which I'm having problems with but I'm anticipating you won't be able to reproduce. I can send you a web link to show you the actual problem but I'd rather not post that URL here.

Thanks again.

**Comment by JimBobSquarePants** [comment] 2015-11-08 12:41
Hey there, 

Can you try reattaching that gif please so I can see what is going on.

Cheers

**Comment by jstrugnell** [comment] 2015-11-09 21:55
Sorry, I thought I had attached. I'll try again... 
![camps_180915_300x320](https://cloud.githubusercontent.com/assets/743352/11047873/9160f028-872c-11e5-80af-419f92200580.gif)

**Comment by JimBobSquarePants** [comment] 2015-11-10 01:30
Thanks, I'll try and have a look tonight :smile:

**Comment by JimBobSquarePants** [comment] 2015-12-01 09:45
I've been testing your image but there's been no discernible quality loss outwith the acceptable loss due to pixel removal on resize.  I'm gonna close this for now unless you have any objections.

![quality](https://cloud.githubusercontent.com/assets/385879/11497293/1fb26140-986c-11e5-8ee8-bbdb5e38a5db.gif)

**Closed by JimBobSquarePants** 2015-12-01 09:45 UTC
Labels: V2
