### ISSUE TITLE
OutOfMemoryException big pictures

### ISSUE THREAD

**Issue by goldenalfer** [JimBobSquarePants/ImageProcessor#385] opened 2016-05-18 12:42 UTC
In my web application I need to work with images with sizes 1000-6000 px width. But ImageProcessorCore generates OutOfMemotyException with 5000x3500px image.

This my scenario:
1. User is uploading an image
2. Web site should save this image and make several copies with different sizes (160px, 320px, 480px, 720px, 1080px heights)

But ImageProcessor generates OutOfMemotyException on step of reading Image.

For testing I created console application with this code

    using (FileStream stream = File.OpenRead("..."))
    using (Image image = new Image(stream))
    using (FileStream output = File.OpenWrite("..."))
    {
    	image.Resize(0, 1080).SaveAsJpeg(output);
    }

After this line 
`using (Image image = new Image(stream))`

we have +270 MB memory usage. Is it really needed so many memory for loading this image?

Is there any tricks to work with my images using ImageProcessorCore?

Image:
![2w4wl7xil8_original](https://cloud.githubusercontent.com/assets/1396956/15358703/80c8306e-1d27-11e6-8bc9-699fd92806e2.JPG)

**Comment by JimBobSquarePants** [comment] 2016-05-18 13:56
Hi @goldenalfer 

I just edited your question slightly since you were referring to ImageProcessor when you, in fact, meant ImageProcessorCore.

I just tested the Image locally on my laptop and was able to resize it along with other images within my unit tests with no issues.

First off, I must stress, ImageProcessorCore is still most definitely an alpha so you shouldn't be using it in a production environment yet. 

Secondly I'll explain the memory usage. 

Each pixel within the image is made up of four floats (I do this over using bytes to interop with `Vector4` for performance and also for algorithmic accuracy) This uses 16 bytes per pixel.

This means that for you image the file size will be 

`5184 x 3456 x 16 = 286654464 bytes which equals 273.375 MB `

Doing the job with the `ImageFactory` code which uses bytes costs 191.957 MB so I've actually kept it pretty lean.

Your image is quite large and I've seen `System.Drawing` fail with less before. The out of memory exception is not caused by your machine running out of total memory but out of contiguous memory.

What is your machine setup? I have 8GB of RAM on a 64bit machine. Are you testing within the built in Visual Studio server? That usually runs at 32 bits which gives you a lot less memory to play with.

Cheers

James

**Comment by goldenalfer** [comment] 2016-05-19 05:34
OK, I understood.

My machine setup is 12 MB of RAM on 64bit Windows desktop. I'm using IISExpress.

Console application works without exceptions, but asp.net 5 mvc application with file uploading by user generates OutOfMemoryException.

**Comment by JimBobSquarePants** [comment] 2016-05-19 06:10
Ah! It's IISExpress that's your issue then. That runs 32bit by default.

You can change that by following the instructions here. The settings are the same for both VS 2013 and VS 2015.

https://www.exceptionnotfound.net/using-64-bit-iis-express-in-visual-studio-2013/

**Comment by goldenalfer** [comment] 2016-05-19 21:00
Understood. Thx

**Comment by JimBobSquarePants** [comment] 2016-05-19 23:36
Excellent. I'm going to close this now.

**Closed by JimBobSquarePants** 2016-05-19 23:36 UTC
Labels: core

**Comment by bilauca** [comment] 2016-10-08 14:04
Hi. I'm using ImageProcessorCore too, and an uploaded image of 14 kb becomes 4mb. Any idea how to tweak the library. It's mandatory for me to use .NET Core.
