### ISSUE TITLE
Azure App Service crash when ImageProcessor is trying to trim the cache

### ISSUE THREAD

**Issue by MikaelEliasson** [JimBobSquarePants/ImageProcessor#723] opened 2019-01-31 14:43 UTC
### Prerequisites
Version: 2.6.2.25
Problem exist in both RELEASE and DEBUG: Not sure, we don't really know how to reproduce it on demand

### Description
We are using ImageProcessor in an AzureWebsite with the AzureBlobCache. Since about 2019-01-15 we started seeing crashes of our app service (Not broken requests, the whole application crashes with the error `0xE0434352 - CLR Exception`). After investigating a dump file we got this Stack trace

```
STACK_TEXT:
6e7df028 06fe37fe UNKNOWN!System.Threading.Tasks.Task.Wait+0xe6
6e7df03c 36c07caa UNKNOWN!ImageProcessor.Web.Caching.ImageCacheBase+CacheTrimmer.TimerRelease+0xaa
6e7df068 36c07beb UNKNOWN!ImageProcessor.Web.Caching.ImageCacheBase+CacheTrimmer+__c__DisplayClass8_0._ScheduleTrimCache_b__0+0x13
6e7df06c 24bcd9c9 UNKNOWN!System.Threading.TimerQueueTimer.CallCallbackInContext+0x31
6e7df070 24bcd6ae UNKNOWN!System.Threading.ExecutionContext.RunInternal+0x106
6e7df0e0 24bca907 UNKNOWN!System.Threading.ExecutionContext.Run+0x17
6e7df0f4 24bca678 UNKNOWN!System.Threading.TimerQueueTimer.CallCallback+0x110
6e7df12c 24bca144 UNKNOWN!System.Threading.TimerQueueTimer.Fire+0xcc
6e7df16c 24bc811b UNKNOWN!System.Threading.TimerQueue.FireNextTimers+0x133
6e7df1ac 24bc7fd2 UNKNOWN!System.Threading.TimerQueue.AppDomainTimerCallback+0x22
```  

We are actually not sure what's exactly is causing this and we don't really know how to reproduce this. Worth to know is that we fairly recently upgraded to the newest version of ImageProcessor. We also did an update to .net 4.7.2 from 4.6.1.  

We also have had way more traffic then ever before in january. 

We have disabled the cache trimming for now, we will release that tomorrow to see if that solves the problem.  

### Steps to Reproduce
Sorry, I wish I knew but we don't see it in development. 

### System Configuration

- ImageProcessor version: 2.6.2.25
- ImageProcessor.Web version (if applicable): 4.9.3.25
- Other ImageProcessor packages and versions: 
- - Web.Config: 2.4.1.19
- - ImageProcessor.Web.Plugins.AzureBlobCache: 1.4.2.19
- Environment (Operating system, version and so on): Azure App Service (asp.net mvc)
- .NET Framework version: 4.7.2
- Additional information:

cache.config
```
<?xml version="1.0" encoding="utf-8"?>
<caching currentCache="AzureBlobCache">
  <caches>
    <cache name="DiskCache" type="ImageProcessor.Web.Caching.DiskCache, ImageProcessor.Web" maxDays="365" browserMaxDays="7">
      <settings>
        <setting key="VirtualCachePath" value="~/app_data/cache" />
      </settings>
    </cache>
    <cache name="AzureBlobCache" type="Bokio.Infrastructure.AzureBlobCacheFromAppSettings, Bokio" maxDays="365">
      <settings>
        <setting key="CachedStorageAccount" value="***" />
        <setting key="CachedBlobContainer" value="cached-images" />
        <setting key="UseCachedContainerInUrl" value="false" />
        <setting key="SourceStorageAccount" value="***" />
        <setting key="SourceBlobContainer" value="***" />
        <setting key="StreamCachedImage" value="true" />
      </settings>
    </cache>
  </caches>
</caching>
```
We do also use a CDN in Azure for this. Relevant setting:
`AzureBlobCache.CachedCDNTimeout: 1000 `

**Comment by MikaelEliasson** [comment] 2019-02-08 07:28
Have not spoken to Azure Support. I'm not exactly sure what to get from them.

After 8 days without the cleaner active we had no crashes at all compared to like 5+ per day before that. Maybe we should simply run without the cleaner. It doesn't really create a problem for us and as you say it adds extra traffic + some complexity with the background scheduling that could cause instability.

**Comment by JimBobSquarePants** [comment] 2019-02-10 09:35
@MikaelEliasson I'm changing the way url based locking is happening in the next release which should prevent any further possibility of deadlocking which I think may be the cause here. It might be an idea to give it a try in your environment once I release though, as I said, it creates a lot of extra traffic so maybe not.

**Comment by JimBobSquarePants** [comment] 2019-02-11 12:48
I'm closing this as I think I have it fixed with the latest release of ImageSharp.Web and ImageProcessor.Web.Plugins.AzureBlobCache

**Closed by JimBobSquarePants** 2019-02-11 12:48 UTC

**Comment by nalinasanka** [comment] 2020-12-15 04:28
Hi MikaelEliasson and JimBobSquarePants ,

We are also facing sporadic trim cache error starting from recently in Production. Just want to confirm with you, if we set **trimCache="false"** in our cacheAzure config will it stop Wep App crashes? Please see below stack error 

at ImageProcessor.Web.Caching.ImageCacheBase.CacheTrimmer.TimerRelease
at System.Threading.ExecutionContext.RunInternal
at System.Threading.ExecutionContext.Run
at System.Threading.TimerQueueTimer.CallCallback
at System.Threading.TimerQueueTimer.Fire
at System.Threading.TimerQueue.FireNextTimers
at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass7.<CreateCallbackVoid>b__5
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
at ImageProcessor.Web.Episerver.Azure.AzureBlobCache.<<TrimCacheAsync>b__10_0>d.MoveNext
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
at ImageProcessor.Web.Caching.ImageCacheBase.CacheTrimmer.<PerformTrim>d__9.MoveNext
at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.<DeleteBlobImpl>b__33
at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T]

And we are using below dll versions
* ImageProcessor 2.8.0
* ImageProcessor.Plugins.WebP 1.3.0
* ImageProcessor.Web 4.11.0
* ImageProcessor.Web.Config 2.6.0
* Other ImageProcessor packages
   - ImageProcessor.Web.Episerver 5.5.0.35788
   - ImageProcessor.Web.Episerver.Azure 5.5.0.35789

Your valuable comments highly appreciated, since we wont stop sudden web app crashes in Production.

Thank you.

**Comment by JimBobSquarePants** [comment] 2020-12-15 11:46
I'm afraid we cannot comment on previous versions. In addition those Episerver packages are not part of this repository. 

However. Setting `trimCache="false"` will disable cache trimming (which is unnecessary on Azure Storage anyway.)
