### ISSUE TITLE
Out of webroot cache generates strange issues intermittently

### ISSUE THREAD

**Issue by akuryan** [JimBobSquarePants/ImageProcessor#561] opened 2017-02-23 09:33 UTC
### Description
When using out-of-webroot cache, ImageProcessor sometimes stops working (so, some images show up, some - not). If tested directly in browser by sending different query strings - image will be never rendered.

I tries with both relative path ( ~/../imageCache ) and absolute one ( D:\Data\Inetpub\imageCache ).

Rights assigned on imageCache is (all full control):

- IUSR 
- Applicationpool user

### Steps to Reproduce

When using DiskCache, setup `<setting key="VirtualCachePath" value="~/../imageCache" />
`
On startup, some images will be rendered and saved to cache folder, but then - they will stop working.

If I use default setting - `<setting key="VirtualCachePath" value="~/app_data/cache" />` - then images rendered correctly all the time

### System Configuration

- ImageProcessor version: 2.5.2.0
- ImageProcessor.Web version (if applicable): 4.8.2.0
- Other ImageProcessor packages and versions:
- Environment (Operating system, version and so on): Windows 2008 R2
- .NET Framework version: 4.5
- Additional information:

**Comment by akuryan** [comment] 2017-02-23 09:57
Here is some more data. After each build, we are using LinkChecker to check links on web app.
Here is report, generated when `<setting key="VirtualCachePath" value="~/../imageCache" />`:

> Site http://myWebAppURI/ was checked for broken links in 2 level recursion depth. There was 36 broken links found.
Coloured values shows comparisson against previous build if it is retrievable
Link https://myWebAppURI/media/2325/google-play.png?width=128&height=42, referred from https://myWebAppURI/gids/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/media/2324/app-store.png?width=128&height=42, referred from https://myWebAppURI/gids/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/media/2128/logo-new-heroes.jpg?width=259px&height=175px, referred from https://myWebAppURI/organisatieonderzoek/dienstverlening/leeronderzoek-ontwikkelonderzoek/future-of-learning/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/media/1928/fersai.jpg?mode=crop&width=80&height=65&rnd=131033944980000000, referred from https://myWebAppURI/opleidingen/leergang-loopbaanadviseur/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/media/1697/ret-op-een-rijtje.jpg?width=250&height=350, referred from https://myWebAppURI/coaching/opleidingsinstituut-voor-coaches/boekentips-coaching/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/media/1696/trainingen-ontwerpen.jpg?width=250&height=350, referred from https://myWebAppURI/coaching/opleidingsinstituut-voor-coaches/boekentips-coaching/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/media/1695/hoe-boek.jpg?width=250&height=350, referred from https://myWebAppURI/coaching/opleidingsinstituut-voor-coaches/boekentips-coaching/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/en/site-data/questions/questions-group-1/ongemotiveerd-een-training-volgen-heeft-dat-wel-zin/, referred from https://myWebAppURI/organisatieonderzoek/web-model/ is generating error 'TooManyRedirects: Exceeded 10 redirects.'
Link https://myWebAppURI/media/1667/goed-voor-de-groep.jpg?width=250&height=350, referred from https://myWebAppURI/coaching/opleidingsinstituut-voor-coaches/boekentips-coaching/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/media/1876/schema-tlc-en-executive-coaching.jpg?width=627px&height=105px, referred from https://myWebAppURI/coaching/coaching-voor-jezelf/executive-coaching/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/media/1928/fersai.jpg?mode=crop&width=80&height=65&rnd=131033944980000000, referred from https://myWebAppURI/opleidingen/leadership-circle-profile-certification/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/media/1928/fersai.jpg?mode=crop&width=80&height=65&rnd=131033944980000000, referred from https://myWebAppURI/opleidingen/orsc-intermediate-crr-global/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/media/1928/fersai.jpg?mode=crop&width=80&height=65&rnd=131033944980000000, referred from https://myWebAppURI/opleidingen/co-active-coaching-fundamentals-cti/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/media/1906/foto-jacq-1-15022016.jpg?mode=crop&width=80&height=65&rnd=131033945170000000, referred from https://myWebAppURI/opleidingen/orsc-fundamentals-crr-global/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/media/2819/snu_schema.jpg?width=426&height=283, referred from https://myWebAppURI/university/missie-visie/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/media/1964/teamwork.jpg?mode=crop&width=72&height=72&rnd=131033925540000000, referred from https://myWebAppURI/teamontwikkeling/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/media/1798/senn_2015_jos_09.jpg?mode=crop&width=72&height=72&rnd=131030455360000000, referred from https://myWebAppURI/e-learning/new-heroes/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/case/global-mentoring-programma-bij-frieslandcampina/, referred from https://myWebAppURI/incompany-en-maatwerk/onze-klanten/industrie/ is generating error '404 Not found'
Link https://myWebAppURI/case/global-mentoring-programma-bij-frieslandcampina/, referred from https://myWebAppURI/incompany-en-maatwerk/onze-klanten/industrie/ is generating error '404 Not found'
Link https://myWebAppURI/case/structurele-opleiding-en-ontwikkeling-uitvaartverzorgers-cooperatie-dela/, referred from https://myWebAppURI/incompany-en-maatwerk/onze-klanten/gezondheidszorg/ is generating error '404 Not found'
Link https://myWebAppURI/case/structurele-opleiding-en-ontwikkeling-uitvaartverzorgers-cooperatie-dela/, referred from https://myWebAppURI/incompany-en-maatwerk/onze-klanten/gezondheidszorg/ is generating error '404 Not found'
Link https://myWebAppURI/media/1318/stefanie.jpg?mode=crop&width=80&height=65&rnd=131033945870000000, referred from https://myWebAppURI/opleidingen/beinvloedingsvaardigheden/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/media/1318/stefanie.jpg?mode=crop&width=80&height=65&rnd=131033945870000000, referred from https://myWebAppURI/opleidingen/coachend-leidinggeven/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/media/1317/rosemarie.jpg?mode=crop&width=80&height=65&rnd=131033946750000000, referred from https://myWebAppURI/opleidingen/goed-waarnemen-juist-interpreteren-en-effectief-communiceren/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/media/1318/stefanie.jpg?mode=crop&width=80&height=65&rnd=131033945870000000, referred from https://myWebAppURI/opleidingen/lean-management/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/media/1318/stefanie.jpg?mode=crop&width=80&height=65&rnd=131033945870000000, referred from https://myWebAppURI/opleidingen/timemanagement/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/media/1315/prisca2kopie.jpg?mode=crop&width=80&height=65&rnd=131033946270000000, referred from https://myWebAppURI/opleidingen/assertiviteitstraining-intensief-hbowo/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/media/1316/judith.jpg?mode=crop&width=80&height=65&rnd=131033946490000000, referred from https://myWebAppURI/opleidingen/beginnen-met-leidinggeven/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/media/1316/judith.jpg?mode=crop&width=80&height=65&rnd=131033946490000000, referred from https://myWebAppURI/opleidingen/leidinggeven-zonder-macht/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/media/1317/rosemarie.jpg?mode=crop&width=80&height=65&rnd=131033946750000000, referred from https://myWebAppURI/opleidingen/versterken-van-persoonlijke-kracht/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/media/1317/rosemarie.jpg?mode=crop&width=80&height=65&rnd=131033946750000000, referred from https://myWebAppURI/opleidingen/effectief-projectmatig-werken/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/media/1970/spiegel.jpg?mode=crop&width=72&height=72&rnd=130988202160000000, referred from https://myWebAppURI/persoonlijke-ontwikkeling/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/media/1971/women-1920x1080.jpg?mode=crop&width=72&height=72&rnd=130988201850000000, referred from https://myWebAppURI/persoonlijke-ontwikkeling/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/media/2584/stolp.png?width=500&height=398.39572192513367, referred from https://myWebAppURI/blog/ is generating error 'Timeout: HTTPSConnectionPool(host='myWebAppURI', port=443): Read timed out.'
Link https://myWebAppURI/blog/de-kompasvisie-ambitie-en-talent-als-motor-voor-verandering/, referred from https://myWebAppURI/blog/ is generating error '404 Not found' 

Not all, but pretty big part of images are generating Read timed out. If I request them directly in browser with same or different query string - they are loading forever,

However, as soon as `<setting key="VirtualCachePath" value="~/app_data/cache" />` is back - all images error are gone:

> Site http://myWebAppURI/ was checked for broken links in 2 level recursion depth. There was 7 ⇓ 36 broken links found.
Coloured values shows comparisson against previous build if it is retrievable
Link https://myWebAppURI/en/site-data/questions/questions-group-1/ongemotiveerd-een-training-volgen-heeft-dat-wel-zin/, referred from https://myWebAppURI/organisatieonderzoek/web-model/ is generating error 'TooManyRedirects: Exceeded 10 redirects.'
Link https://myWebAppURI/case/global-mentoring-programma-bij-frieslandcampina/, referred from https://myWebAppURI/incompany-en-maatwerk/onze-klanten/industrie/ is generating error '404 Not found'
Link https://myWebAppURI/case/global-mentoring-programma-bij-frieslandcampina/, referred from https://myWebAppURI/incompany-en-maatwerk/onze-klanten/industrie/ is generating error '404 Not found'
Link https://myWebAppURI/case/structurele-opleiding-en-ontwikkeling-uitvaartverzorgers-cooperatie-dela/, referred from https://myWebAppURI/incompany-en-maatwerk/onze-klanten/gezondheidszorg/ is generating error '404 Not found'
Link https://myWebAppURI/case/structurele-opleiding-en-ontwikkeling-uitvaartverzorgers-cooperatie-dela/, referred from https://myWebAppURI/incompany-en-maatwerk/onze-klanten/gezondheidszorg/ is generating error '404 Not found'
Link https://myWebAppURI/blog/de-kompasvisie-ambitie-en-talent-als-motor-voor-verandering/, referred from https://myWebAppURI/blog/ is generating error '404 Not found'

**Comment by akuryan** [comment] 2017-02-23 11:37
Timeouts are generated when using LinkChecker. In Chrome it was saying "Waiting for available socket" in status, while in Network tab all images, which is not in the cache was in pending state (same was observed in Edge or Firefox). All checks was done in incognito modes or with completely clear cache

**Comment by JimBobSquarePants** [comment] 2017-02-23 20:19
Were there any error messages with Edge and Firefox? or anything in the server error logs?

**Comment by akuryan** [comment] 2017-02-27 06:06
I was able to see it in Edge, Firefox, headless Linkchecker - so, it does not seems to be browser related. I have not seen any errors in server logs, but will recheck it today for sure

**Comment by JimBobSquarePants** [comment] 2017-02-27 10:40
You mean the message "Waiting for available socket" was present in all? As far as I can see that's a Chrome specific message. 

I can only recommend building from source and attaching a debugger at this point so we can see what is holding onto resources.

**Comment by akuryan** [comment] 2017-02-27 10:50
Yes, I saw this message in Chrome; Edge was not displaying; LinkChecker does not display it also :) 
I will try to look at sources as soon as I have some time

**Comment by JimBobSquarePants** [comment] 2017-02-27 11:02
Thanks! Fingers crossed it becomes obvious.

**Comment by akuryan** [comment] 2017-02-28 13:08
It is not reproduced in my local environment (Win 10) :( And I could not debug on production. Will try to build replica in Hyper-V

**Comment by JimBobSquarePants** [comment] 2017-02-28 21:41
Good luck!

**Comment by rbottema** [comment] 2017-05-03 12:59
Today I ran into the same problem with the same ImageProcessor version (4.8.2). The cache directory we use is a virtual directory '\~/app_data/cache' which points to '\~/../App_Data_cache'. The symptoms we see are the requests hanging, eventually filling up IIS' open connections. dotTrace shows the following typical hanging thread:
![image](https://cloud.githubusercontent.com/assets/963169/25661434/ecc7bd78-3010-11e7-9263-36b2b40ebc5c.png)

Let me know if you are able to reproduce this, or if you need more information from us.

**Comment by JimBobSquarePants** [comment] 2017-05-03 13:36
Hi @rbottema 

I've not been able to replicate this at all and could really do with some help getting to the bottom of it. If there is anything you can do please let me know. I'm assuming we're sticking on RewritePath.

Cheers

James

**Comment by rbottema** [comment] 2017-05-03 13:43
I just sent you a mail. Let's get to the bottom of this =)

**Comment by JimBobSquarePants** [comment] 2017-10-17 04:13
I think I've figure out what the cause was.  

Using `Response.End()` causes a `ThreadAbortException` which was going unhandled causing requests to hang.

https://github.com/JimBobSquarePants/ImageProcessor/blob/01bc20832bb1c81b91bbc8ab7343a2fe517e70e4/src/ImageProcessor.Web/Caching/DiskCache.cs#L346

If you can give the latest version a go it should be fixed.

https://www.nuget.org/packages/ImageProcessor.Web/4.8.7

**Closed by JimBobSquarePants** 2017-10-17 04:13 UTC
