### ISSUE TITLE
Loading png image in an ImageFactory and saving it without any processing increases its size

### ISSUE THREAD

**Issue by MissaouiChedy** [JimBobSquarePants/ImageProcessor#575] opened 2017-04-04 10:43 UTC
### Description
When loading a png image in an `ImageFactory` and then saving it back directly without any processing, as in the following snippet:
```
byte[] png = File.ReadAllBytes(imageFile);
using (MemoryStream inStream = new MemoryStream(png))
{
       using (MemoryStream outStream = new MemoryStream())
       {
             using (ImageFactory imageFactory = new ImageFactory())
             {
                 imageFactory.Load(inStream)
                                    .Save(outStream);
              }
         }
}
```
The resulting image is bigger in size than the initial image. Furthermore when doing the same thing to a jpeg image it gets smaller.

This behavior is a bit confusing. I think that the `ImageFactory` should not alter the image when it is only loaded and not processed. 

Note that I tested with DEBUG and RELEASE configurations, this issue is present in both.

I understand that it is easy to work around this issue: just don't load images that are not going to be processed. But I thought I would give an evantually useful heads up.
 
### Steps to Reproduce
You can find in this [link a small console application that demonstrates the issue](https://drive.google.com/open?id=0B7uQsylgRSrCejhHbVB0cnJzdjQ).

### System Configuration

- ImageProcessor version: 2.5.3
- Environment (Operating system, version and so on): Windows 10 x64
- .NET Framework version: .NET 4.5.2

**Comment by JimBobSquarePants** [comment] 2017-04-04 10:49
Duplicate of https://github.com/JimBobSquarePants/ImageProcessor/issues/98

Essentially blame whoever created the System.Drawing png encoder

**Closed by JimBobSquarePants** 2017-04-04 10:49 UTC
