### ISSUE TITLE
#413 fault

### ISSUE THREAD

**Issue by neilw1** [JimBobSquarePants/ImageProcessor#417] opened 2016-06-28 18:45 UTC
Hello,
 I'm afraid it doesn't work (the update to fix Alpha). As soon as you call the hue method (e.g. ifac.Hue(0)) it is adding a positive hue to the image and turning everything reddish. It looks like you've got an index offset issue as it's the equivalent of adding 1 to the hue. In my case it is pictures of people and they all get a red face :)

**Comment by neilw1** [comment] 2016-06-28 18:47
what I mean is, if I apply Hue(-1) then the image is as it was loaded. When you call Hue(0) it becomes Hue(1) out of your code.

**Comment by neilw1** [comment] 2016-06-28 19:00
I can't recall testing it with other versions, I was doing so much work but it's definitely not an issue 2.3.3.0

In hue.cs could this be the problem, when you merged the rotate and degree code?

    if (this.ShouldProcess && degrees > 0)

**Comment by neilw1** [comment] 2016-06-28 19:06
Yep, I've retried 2.4.1.0 and all is well. Use 2.4.2.0 and it effectively applies +1 to whatever hue you pass in, e.g. Hue(0) becomes Hue(-1). So in code if I due .Hue(data.Hue-1) it works as normal.

Hope this helps.

**Comment by JimBobSquarePants** [comment] 2016-06-28 22:53
Hi there. I have a few questions for you.

Firstly. Did you read the [contribution guidelines](https://github.com/JimBobSquarePants/ImageProcessor/blob/Core/contributing.md) that are highlighted to you every time you raise an issue?

Secondly. How is this issue related at all to issue #413 ? At no point in that issue do you mention the hue calculation being an issue. Issue #413 is a `System.ArgumentException` caused by a lack of property items within the image. 

>Yep, I've retried 2.4.1.0 and all is well. Use 2.4.2.0 and it effectively applies +1 to whatever hue you pass in, e.g. Hue(-1) becomes Hue(0). So in code if I due .Hue(data.Hue-1) it works as normal.

Your original issue was raised against v2.4.1 so all could not possible have been well! 

Please remember that you are working against a project that as is **ran by someone in their spare time**. There is nothing to stop you forking the repo and taking the time to investigate and fix issues yourself.

I'm going to close this issue for now and will reopen it once you have provided the necessary information as indicated in the [contribution guidelines](https://github.com/JimBobSquarePants/ImageProcessor/blob/Core/contributing.md) which will allow me to continue.

**Closed by JimBobSquarePants** 2016-06-28 22:53 UTC
Labels: not enough information provided

**Comment by neilw1** [comment] 2016-06-29 09:18
Because it was OK in the previous version and not the next day, so I
presumed the only change was to this bug I raised.

Simply apply hue of zero to an image and it gets modified with a hue of 1,
ie it alters the original to a reddish tint.

I've create a new case instead.
