### ISSUE TITLE
Feature Request: Interface for supporting output for Cached Images

### ISSUE THREAD

**Issue by warrenbuckley** [JimBobSquarePants/ImageProcessor#120] opened 2015-01-15 16:39 UTC
Hi James,
Great work on ImageProcessor. I use it in our sites with Umbraco as it's bundled/shipped with it.

I have a feature request to implement a way to allow us to specify how and where the cached images once gone through the pipeline are stored and retrieved from.

For example I would :heart: that if it was possible to store the cached output images on Azure Blob Storage or Amazon S3 storage.

The full usecase of my feature request is as follows:
* Use Umbraco
* Use Umbraco Azure Blob Storage Provider
* Ensure all original images uploaded in the media section are stored on Azure
* An image picked from the media library is passed through to imageprocessor library
* The resulting output image (crop/resize etc...) is stored on Azure
* Any subsequent requests for the image in the cache are retrieved from Azure directly

Any questions James about this, that does not make sense please let me know.

Cheers,
Warren

**Comment by kristianschneider** [comment] 2015-01-15 17:11
this proje t might be woeth snooping at:https://github.com/AliSheikhTaheri/AST-Azure-Media-Sync

**Comment by Jeavon** [comment] 2015-01-15 18:44
I too have been thinking about this :) My current very early idea is something like this:

Use ImageProcessingModule.OnPostProcessing to capture a image being cached
Copy the newly cached image to the folder of the original image using the IFileSystem, we need to extract the original image path (not sure if it's currently available)
Save the original full ImageProcessor.Web Url with Querystring with the path of the static file saved to the IFileSystem (somewhere, maybe static JSON file) and create a dictionary object cache of this data for fast retrieval 
Create a wrapper method of GetCropUrl which checks this cache and returns the path of the static asset if it exists (first request it won't, so user will get normal IP.Web Url)
This new method would also support a setting for a absolute url so you can plug in your CDN url and it will always return with that prefixed.

There are already several packages that sync from Umbraco IFileSystem to Azure Blob or S3 so you could choose which one to use.

Obviously this is specific to using ImageProcessor in Umbraco, I'm sure it might be possible to come up with something that was ImageProcessor standalone also and build on top of that....

Brain dump over!

**Comment by JimBobSquarePants** [comment] 2015-01-15 22:15
Crikey Jeavon, that's a long trip! I think it would maybe work but I would worry about performance plus the DiskCache check would fail if the file based cached image was removed.

What we need to concentrate on is a good interface design not the specific implementations. I've put thought to it before and I've not managed to come up with something that'll work properly. Together I think we can though I'm sure.

The problem is there's too many specific parameters getting passed around in the HttpModule. We'd need to clean that up. 

https://github.com/JimBobSquarePants/ImageProcessor/blob/master/src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs#L362

Also there's the authorisation stuff, that could get moved into the DiskCache implementation of the interface though.

Decoupling is hard.....

**Comment by Shazwazza** [comment] 2015-01-16 01:53
My first thought, since this is Azure - why not attempt to use Web Jobs? You could have a Web Job ensure that the ImageProcessor cached images are synced to blob storage or whatever, then somehow extend the methods that return your the URLs for these images to point to your CDN web path. Basically like an "origin pull" kind of setup. Would that work? If so, seems like that'd be much easier.

**Comment by JimBobSquarePants** [comment] 2015-01-16 10:08
You'd still have the issue of spacing. In order to prevent ImageProcessor from processing the image upon each request you would have to keep the file cached images where they are. 

A pluggable interface based system is definitely what we require. I've made pretty much everything else pluggable so this should be also.

**Comment by warrenbuckley** [comment] 2015-01-16 10:59
@JimBobSquarePants I am not sure I understand the problem with what @Shazwazza has suggested with an Azure WebJob to process these images as a queue or am I being dumb here?!

**Comment by Shazwazza** [comment] 2015-01-16 13:36
It's not processing the images as a job, it's just copying then (sync) to
where you really want them to be

**Comment by JimBobSquarePants** [comment] 2015-01-16 14:13
@warrenbuckley As far as I understand it the solution doesn't mitigate the issue of limited filesystem space since the integrated cache requires files to check against in order to do it's thing and prevent reprocessing on every request. That's why I think an interface driven solution where the caching functionality is performed in each implementation is the only way to correctly solve this.

**Comment by JimBobSquarePants** [comment] 2015-02-27 17:12
Fixed in v4.2.0 Caheck out http://imageprocessor.org/imageprocessor-web/plugins/azure-blob-cache/

**Closed by JimBobSquarePants** 2015-02-27 17:12 UTC
Labels: enhancement, help needed
