### ISSUE TITLE
Heap Corruption in 2.4.2

### ISSUE THREAD

**Issue by crohkohl** [JimBobSquarePants/ImageProcessor#419] opened 2016-06-29 23:50 UTC
I run the following code repeatedly very often:

```c#
using (ImageFactory imageFactory = new ImageFactory(preserveExifData: false))
{
    var request = WebRequest.Create(img.url);

    using (var response = request.GetResponse())
    using (var stream = response.GetResponseStream())
    {

        // Load, resize, set the format and quality and save an image.
        imageFactory.Load(stream);

        imageFactory.Format(new JpegFormat() { Quality = 70 }).Resize(new ResizeLayer(new System.Drawing.Size(250, 250), ResizeMode.Crop, AnchorPosition.Center, true));
        imageFactory.Save(fnameSmall);

        imageFactory.Reset();

        imageFactory.Format(new JpegFormat() { Quality = 70 }).Resize(new ResizeLayer(new System.Drawing.Size(600, 400), ResizeMode.Crop, AnchorPosition.Center, true));
        imageFactory.Save(fnameLarge);
    }
}
```

With the nuget package 2.4.1 everything works fine.
After an update to version 2.4.2 running the same code results in a heap corruption after some time.

There must have been some change between the two versions causing this behaviour.

**Comment by JimBobSquarePants** [comment] 2016-06-30 01:07
I'll have to do a diff but the only change of any significance is in the `Reset` method where I was incorrectly not resetting the current image format.

**Comment by neilw1** [comment] 2016-06-30 15:44
I'm getting issues with 2.4.2 (but I raised another issue for this, I just wanted to see if it might have any bearing/or help with your fault) specifically the image factory Hue method is not working and ends up setting the wrong value.

**Comment by JimBobSquarePants** [comment] 2016-07-01 00:20
@neilw1  I don't think that will be related but I'll have to dig around. 

@crohkohl  I'm not touching anything _I think_ in the unmanaged realm using those methods but I'll double check.

**Comment by JimBobSquarePants** [comment] 2016-07-01 00:57
@crohkohl Do you have any detail on the exact error message?

**Comment by dlemstra** [comment] 2016-07-02 15:43
Maybe this is related to the PixelAccessor you introduced in the last version?

**Comment by crohkohl** [comment] 2016-07-02 18:27
It is a standard heap corruption - mostly difficult to debug due to some
invalid memory accesses.
Maybe there is a problem with thread-safety? I run my code in
Parallel.ForEach(); statement?



2016-07-02 17:43 GMT+02:00 Dirk Lemstra <notifications@github.com>:

**Comment by JimBobSquarePants** [comment] 2016-07-02 23:38
@dlemstra That's actually the new Core code the `PixelAccessor` was added to, the issue is in the Framework ImageFactory branch. I am concerned though about my `FastBitmap` class though as one of my unit tests is suddenly repeatedly failing complaining that I am attempting to access protected memory. I don't know whether it is a test issue as I can run the code in my playground project just fine but something is certainly up. 

Perhaps you could have a look at it for me? You have way more experience in the unmanaged world than I have.
https://github.com/JimBobSquarePants/ImageProcessor/blob/53a3f6c5588d1012925b2959ca7fcf7e8595c60a/tests/ImageProcessor.UnitTests/ImageFactoryUnitTests.cs#L958

On the note of using `fixed` I believe it should be safe as I only fix objects below 85k since they are stored on the small object heap. The garbage collector should't try to move anything there since the referenced object will be in use for the duration of the process which will be miniscule for such small objects.

@crohkohl Yes, it'll definitely be an issue with thread safety. The `Graphics` object in `System.Drawing` is not thread safe and that is definitely where you will be having issues. I'm absolutely amazed that you didn't have any issues before. 

I'll keep this open to allow investigation of the failing unit test but I recommend not using `Parallel.ForEach()` to fix your issue.

**Comment by JimBobSquarePants** [comment] 2016-07-07 02:56
That was reaaaaaaally tricky to debug and fix but I've cracked it. Should get a wee performance boost also.

**Comment by JimBobSquarePants** [comment] 2016-07-07 11:48
New release available on Nuget now.

**Closed by JimBobSquarePants** 2016-07-07 11:48 UTC
Labels: bug, fixed on dev, framework
