### ISSUE TITLE
Background(Color color) does not change the background

### ISSUE THREAD

**Issue by Excludos** [JimBobSquarePants/ImageProcessor#760] opened 2019-07-31 07:46 UTC
Using ImageProcessor v2.7.0.100 on windows 10, with .Net Framework 4.7.1.

`var resizeImage = new ResizeLayer(new Size(200, 300),ResizeMode.Pad, AnchorPosition.Top, true);
imageCanvas.Load(imageFile).BackgroundColor(Color.Purple).Resize(resizeImage).Save(exportName);`

The color of the padded area stays black.

**Comment by JimBobSquarePants** [comment] 2019-07-31 09:21
Duplicate of #719 

The API is imperative. This means that the commands run in the order in which they are supplied. 

You need to resize first then set the background color. 

``` c#
var resizeImage = new ResizeLayer(new Size(200, 300), ResizeMode.Pad, AnchorPosition.Top, true); 

imageCanvas
.Load(imageFile)
.Resize(resizeImage)
.BackgroundColor(Color.Purple)
.Save(exportName);
```

**Closed by JimBobSquarePants** 2019-07-31 09:21 UTC

**Comment by Excludos** [comment] 2019-07-31 11:10
That's fair, but the documentation should really reflect that. It doesn't at all make logical sense that you can only change the color of the background after you add it (Ie: You wouldn't fill in part of an image in paint and only afterwards change the color of the fill)

**Comment by JimBobSquarePants** [comment] 2019-07-31 14:43
@Excludos It's a fluent API. If you were using System.Linq (or any other fluent API) you wouldn't expect anything other than imperative application of each method so I don't understand why you would expect this to.
