### ISSUE TITLE
Sporadic issue with encoder

### ISSUE THREAD

**Issue by dwdickens** [JimBobSquarePants/ImageProcessor#454] opened 2016-08-17 12:18 UTC
![works fine](https://cloud.githubusercontent.com/assets/13432550/17735920/558dae04-64c8-11e6-8dd7-2c9d7408208b.jpeg)

![throws error](https://cloud.githubusercontent.com/assets/13432550/17735867/0b0d0c80-64c8-11e6-8ee6-02626d98913a.JPG)
Loading an image file and then attempting to save it sometimes fails, depending on the picture. It makes no different whether manipulation is performed. First attached picture works. Second fails.

I have added a tempStream to illustrate the problem. Certain pictures cause the following error: 	ImageProcessorCore.ImageFormatException: Missing SOS marker.
   at ImageProcessorCore.Formats.JpegDecoderCore.Decode[T,TP](Image`2 image, Stream stream, Boolean configOnly)

Attempting to save the tempStream to a file results in an invalid jpeg, so I think the error is in the encoding not decoding.

Running ASP.NET core RTM
"ImageProcessorCore": "1.0.0-alpha-1009"

Code:

      public abcde SaveUpload(IFormFile formFile)
           {                                   
            try
            {               

                string filePath = "insert name and path.jpeg";

                using (MemoryStream stream = new MemoryStream())
                using (MemoryStream tempStream = new MemoryStream())
                using (FileStream output = File.OpenWrite(filePath))                
                {

                    ImageProcessorCore.Image image = new ImageProcessorCore.Image(formFile.OpenReadStream());

                    image.SaveAsJpeg(tempStream, 75);

                    ImageProcessorCore.Image testImage = new ImageProcessorCore.Image(tempStream); //throws error for certain images

                    tempStream.WriteTo(output);

                }

      catch {...}
      }

**Comment by JimBobSquarePants** [comment] 2016-08-17 12:39
Jpeg is hard :cry: 

Thanks for raising this. I'll see what I can do.

**Comment by dlemstra** [comment] 2016-08-17 13:08
@JimBobSquarePants How do we know which version of the code was used for 1.0.0-alpha-1009?

**Comment by JimBobSquarePants** [comment] 2016-08-17 13:53
@dlemstra It's the latest build. 

https://ci.appveyor.com/project/JamesSouth/imageprocessor/history

**Comment by dlemstra** [comment] 2016-08-17 13:55
Okay thanks was wondering if this was due to my EXIF changes. Can you reproduce the issue with v1.0.0.996 @dwdickens ?

**Comment by dwdickens** [comment] 2016-08-18 12:33
Problem disappears with v1.0.0.996.
While the error is being thrown by the decoder, I think the problem lies with the encoder. When I had the encoder writing straight to a filestream, it was creating a .jpeg that couldn't be opened by any image viewer. I interpolated the tempStream as a means to identify when the problem was occurring.

**Comment by JimBobSquarePants** [comment] 2016-08-18 12:52
Interesting thanks!

I'm actually testing it against the latest source right now and I cannot get it to encode. Could you please do me a favour and give the very latest download on Myget a try?

**Comment by dwdickens** [comment] 2016-08-18 13:13
I just tried it using "1.0.0-alpha-1011", and it's back to throwing an error. BTW, the beach picture I attach above does not work, and the city picture works. The beach picture appears to have exif, and the city picture doesn't. Given the comments above and the recent changes, maybe that's the issue?

**Comment by JimBobSquarePants** [comment] 2016-08-18 13:27
@dwdickens Thanks. You've just confirmed my findings. I just disabled EXIF and it worked.

@dlemstra It looks like EXIF is breaking the image encoding. It could be something to do with my Rational type but I'm not sure, could you have a look when you can please.

**Comment by JimBobSquarePants** [comment] 2016-08-18 13:47
JPEGsnoop output off image.
The failing one doesn't seem to get past the APP1 marker, Rational seems ok.

```
JPEGsnoop 1.7.3 by Calvin Hass
  http://www.impulseadventure.com/photo/
  -------------------------------------

  Filename: [C:\development\github\ImageProcessor\tests\ImageProcessorCore.Tests\TestOutput\Encode\error.jpg]
  Filesize: [2066987] Bytes

Start Offset: 0x00000000
*** Marker: SOI (xFFD8) ***
  OFFSET: 0x00000000
 
*** Marker: APP0 (xFFE0) ***
  OFFSET: 0x00000002
  Length     = 16
  Identifier = [JFIF]
  version    = [1.1]
  density    = 0 x 96 DPI (dots per inch)
  thumbnail  = 0 x 96
 
*** Marker: APP1 (xFFE1) ***
  OFFSET: 0x00000014
  Length          = 49510
  Identifier      = [Exif]
  Identifier TIFF = 0x[49492A00 08000000]
  Endian          = Intel (little)
  TAG Mark x002A  = 0x002A

  EXIF IFD0 @ Absolute 0x00000026
    Dir Length = 0x000C
    [ImageDescription                    ] = "                               "
    [Make                                ] = "SONY"
    [Model                               ] = "DSC-WX80"
    [Orientation                         ] = 1 = Row 0: top, Col 0: left
    [XResolution                         ] = 350/1
    [YResolution                         ] = 350/1
    [ResolutionUnit                      ] = Inch
    [Software                            ] = "DSC-WX80 v1.00"
    [DateTime                            ] = "2013:08:05 15:47:31"
    [YCbCrPositioning                    ] = Co-sited
    [ExifOffset                          ] = @ 0x011E
    Offset to Next IFD = 0x00009742

  EXIF IFD1 @ Absolute 0x00009760
    Dir Length = 0x000D
    [Compression                         ] = JPEG
    [XResolution                         ] = 72/1
    [YResolution                         ] = 72/1
    [ResolutionUnit                      ] = Inch
    [JpegIFOffset                        ] = @ +0x9848 = @ 0x9866
    [JpegIFByteCount                     ] = 0x[00002918] / 10520
    [YCbCrPositioning                    ] = Co-sited
    Offset to Next IFD = 0x00000000

  EXIF SubIFD @ Absolute 0x0000013C
    Dir Length = 0x0024
    [ExposureTime                        ] = 1/1600 s
    [FNumber                             ] = F3.3
    [ExposureProgram                     ] = Landscape mode
    [ISOSpeedRatings                     ] = 100
    [ExifVersion                         ] = 02.30
    [DateTimeOriginal                    ] = "2013:08:05 15:47:31"
    [DateTimeDigitized                   ] = "2013:08:05 15:47:31"
    [ComponentsConfiguration             ] = [Y Cb Cr .]
    [CompressedBitsPerPixel              ] = 3/1
    [BrightnessValue                     ] = 25954/2560
    [ExposureBiasValue                   ] = 0.00 eV
    [MaxApertureValue                    ] = 882/256
    [MeteringMode                        ] = Pattern
    [LightSource                         ] = unknown
    [Flash                               ] = Flash did not fire
    [FocalLength                         ] = 5 mm
    [MakerNote                           ] = @ 0x0334
    [UserComment                         ] = ""
    [FlashPixVersion                     ] = 01.00
    [ColorSpace                          ] = sRGB
    [ExifImageWidth                      ] = 0x[00001200] / 4608
    [ExifImageHeight                     ] = 0x[00000D80] / 3456
    [ExifInteroperabilityOffset          ] = @ 0x9724
    [FileSource                          ] = DSC
    [SceneType                           ] = A directly photographed image
    [CustomRendered                      ] = Normal process
    [ExposureMode                        ] = Auto exposure
    [WhiteBalance                        ] = Auto white balance
    [DigitalZoomRatio                    ] = 16/16
    [SceneCaptureType                    ] = Landscape
    [Contrast                            ] = 0
    [Saturation                          ] = 0
    [Sharpness                           ] = 0

  EXIF MakerIFD @ Absolute 0x00000352
    Makernote decode option not enabled.

  EXIF InteropIFD @ Absolute 0x00009742
    Dir Length = 0x0002
    [InteroperabilityIndex               ] = "R98"
    [InteroperabilityVersion             ] = 01.00
 
*** Marker: EOI (End of Image) (xFFD9) ***
  OFFSET: 0x0000C17C
```

Snoop of input image
```

JPEGsnoop 1.7.3 by Calvin Hass
  http://www.impulseadventure.com/photo/
  -------------------------------------

  Filename: [C:\development\github\ImageProcessor\tests\ImageProcessorCore.Tests\TestImages\Formats\Jpg\error.jpg]
  Filesize: [6051468] Bytes

Start Offset: 0x00000000
*** Marker: SOI (xFFD8) ***
  OFFSET: 0x00000000
 
*** Marker: APP1 (xFFE1) ***
  OFFSET: 0x00000002
  Length          = 49512
  Identifier      = [Exif]
  Identifier TIFF = 0x[49492A00 08000000]
  Endian          = Intel (little)
  TAG Mark x002A  = 0x002A

  EXIF IFD0 @ Absolute 0x00000014
    Dir Length = 0x000C
    [ImageDescription                    ] = "                               "
    [Make                                ] = "SONY"
    [Model                               ] = "DSC-WX80"
    [Orientation                         ] = 1 = Row 0: top, Col 0: left
    [XResolution                         ] = 350/1
    [YResolution                         ] = 350/1
    [ResolutionUnit                      ] = Inch
    [Software                            ] = "DSC-WX80 v1.00"
    [DateTime                            ] = "2013:08:05 15:47:31"
    [YCbCrPositioning                    ] = Co-sited
    [ExifOffset                          ] = @ 0x011E
    Offset to Next IFD = 0x00009742

  EXIF IFD1 @ Absolute 0x0000974E
    Dir Length = 0x000D
    [Compression                         ] = JPEG
    [XResolution                         ] = 72/1
    [YResolution                         ] = 72/1
    [ResolutionUnit                      ] = Inch
    [JpegIFOffset                        ] = @ +0x9848 = @ 0x9854
    [JpegIFByteCount                     ] = 0x[00002918] / 10520
    [YCbCrPositioning                    ] = Co-sited
    Offset to Next IFD = 0x00000000

  EXIF SubIFD @ Absolute 0x0000012A
    Dir Length = 0x0024
    [ExposureTime                        ] = 1/1600 s
    [FNumber                             ] = F3.3
    [ExposureProgram                     ] = Landscape mode
    [ISOSpeedRatings                     ] = 100
    [ExifVersion                         ] = 02.30
    [DateTimeOriginal                    ] = "2013:08:05 15:47:31"
    [DateTimeDigitized                   ] = "2013:08:05 15:47:31"
    [ComponentsConfiguration             ] = [Y Cb Cr .]
    [CompressedBitsPerPixel              ] = 3/1
    [BrightnessValue                     ] = 25954/2560
    [ExposureBiasValue                   ] = 0.00 eV
    [MaxApertureValue                    ] = 882/256
    [MeteringMode                        ] = Pattern
    [LightSource                         ] = unknown
    [Flash                               ] = Flash did not fire
    [FocalLength                         ] = 5 mm
    [MakerNote                           ] = @ 0x0334
    [UserComment                         ] = ""
    [FlashPixVersion                     ] = 01.00
    [ColorSpace                          ] = sRGB
    [ExifImageWidth                      ] = 0x[00001200] / 4608
    [ExifImageHeight                     ] = 0x[00000D80] / 3456
    [ExifInteroperabilityOffset          ] = @ 0x9724
    [FileSource                          ] = DSC
    [SceneType                           ] = A directly photographed image
    [CustomRendered                      ] = Normal process
    [ExposureMode                        ] = Auto exposure
    [WhiteBalance                        ] = Auto white balance
    [DigitalZoomRatio                    ] = 16/16
    [SceneCaptureType                    ] = Landscape
    [Contrast                            ] = 0
    [Saturation                          ] = 0
    [Sharpness                           ] = 0

  EXIF MakerIFD @ Absolute 0x00000340
    Makernote decode option not enabled.

  EXIF InteropIFD @ Absolute 0x00009730
    Dir Length = 0x0002
    [InteroperabilityIndex               ] = "R98"
    [InteroperabilityVersion             ] = 01.00
 
*** Marker: APP2 (xFFE2) ***
  OFFSET: 0x0000C16C
  Length          = 146
  Identifier      = [MPF]
    Not supported. Skipping remainder.

```

**Comment by JimBobSquarePants** [comment] 2016-08-18 13:49
APP1 marker on encoded image is two bytes shorter than original

**Comment by dlemstra** [comment] 2016-08-18 15:28
I probably forgot to add two bytes to the length. Will have a look when I get home.

**Comment by dlemstra** [comment] 2016-08-18 18:11
Can you test with 1012 @dwdickens? The patch that I just pushed should resolve the issue.

**Comment by dwdickens** [comment] 2016-08-19 11:58
great works @dlemstra, its working now with 1012. Thanks a million!

**Comment by dlemstra** [comment] 2016-08-19 12:03
You can email me for my bank account number to transfer that million :smiling_imp: .

**Comment by dwdickens** [comment] 2016-08-19 12:06
cheque's in the mail I swear

**Comment by dlemstra** [comment] 2016-08-19 13:06
Okay I'll quit my job then and close this issue.

**Closed by dlemstra** 2016-08-19 13:06 UTC
Labels: bug, core, help needed
